from __future__ import annotations

from dataclasses import dataclass
from typing import Literal
import pandas as pd


@dataclass(frozen=True)
class PaperAccountState:
    """Account snapshot at a completed candle close."""

    timestamp: int
    cash: float
    units: float
    target_position: float
    equity: float


@dataclass(frozen=True)
class PaperFill:
    """Synthetic fill generated by the paper trading engine."""

    timestamp: int
    side: Literal["buy", "sell"]
    fill_price: float
    quantity: float
    cash_after_fill: float
    units_after_fill: float
    equity_after_fill: float


@dataclass(frozen=True)
class PaperTradingResult:
    """Container for paper trading outputs."""

    account_states: list[PaperAccountState]
    account_history: pd.DataFrame
    fills: list[PaperFill]
    initial_cash: float
    ending_cash: float
    ending_units: float
    ending_equity: float
